version: 1.3.{build}
skip_non_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - 7z a xslt-cli-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\CLI\bin\%CONFIGURATION%\xslt-cli.ex*
artifacts:
  - path: xslt-cli-%APPVEYOR_BUILD_VERSION%.zip
deploy:
  release: v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: 7T+aUcPgiRzaxvOIQOEzlgKfK/Ni3aOSI6XM/tahsOx87NRiZ1B0sHuIBJ0KYFUz
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
