version: 1.3.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - 7z a xslt-cli-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\CLI\bin\%CONFIGURATION%\xslt-cli.ex*
artifacts:
  - path: xslt-cli-%APPVEYOR_BUILD_VERSION%.zip
deploy:
  release: xslt-cli-v$(appveyor_build_version)
  description: 'v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: 7T+aUcPgiRzaxvOIQOEzlgKfK/Ni3aOSI6XM/tahsOx87NRiZ1B0sHuIBJ0KYFUz
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
